-- Inserir UNIDADE_MEDIDA
INSERT INTO lazuli.unidade_medida (nome,simbolo,status)
VALUES ('UNIDADE','UN',1);

INSERT INTO lazuli.unidade_medida (nome,simbolo,status)
VALUES ('QUILOGRAMA','KG',1);

INSERT INTO lazuli.unidade_medida (nome,simbolo,status)
VALUES ('LITRO','L',1);


-- Inserir TIPO_PRODUTO
INSERT INTO lazuli.tipo_produto (nome) VALUES ('VENDA');
INSERT INTO lazuli.tipo_produto (nome) VALUES ('INGREDIENTE');


-- Inserir INGREDIENTE
delimiter //

begin
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('AÇUCAR DEMERARA UNIÃO', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('AÇUCAR MASCAVO NATUS', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('AÇUCAR REFINADO', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('ADESIVO LOGO- GRAFICA PONCE- 4X4', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('ADESIVO VENCIMENTO 4X4', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('BASE PARA A TORTA COOKIE- NATAL 26CM', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('BICARBONATO DE SÓDIO-TRISANTI', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('BISCOITO MAISENA', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('BISCOITO OREO', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('BRIGADEIRO 16 GRS- COM FORMINHA (PARA CENTO)', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('BRIGADEIRO 20 GRS- COM FORMINHA', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('BROWNIE (SEM EMBALAGEM)', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('BROWNIE EMBALADO', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('CACAU EM PÓ 100% DONA JURA', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('CACAU EM PÓ 100% SICAO', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('CAIXA 14X14X4- MARROM C/ VISOR', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('CAIXA 15,5 X 7,5 X 3- MARROM P/ 8 BRIGADEIROS', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('CAIXA 15X15X8- BRANCA C/ VISOR', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('CAIXA 19 X 15,5 X 3- MARROM P/ 20 BRIGADEIROS', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('CAIXA 3 BRIGADEIROS- BRANCO 12X4X2,5', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('CAIXA 8 X 8 X 3- MARROM P/ 4 BRIGADEIROS', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('CAIXA DE BOTÃO DE ROSA- BRANCA 6X32X7', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('CAIXA GAVETA BARRA- MARROM 18X10,7X3,7', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('CAIXA GAVETA C/ VISOR (04 DOCES) - ROSE GOLD 4X8X8X', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('CAIXA GAVETA C/ VISOR (04 DOCES)- JARDIM TURQUESA 4X8X8', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('CAIXA GAVETA C/ VISOR (04 DOCES)- TURQUESA 4X8X8', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('CAIXA GAVETA C/ VISOR (12 DOCES)- DOCE JARDIM 4X15X12', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('CAIXA KRAFT (12 DOCES)- COM PORTA FORMA KRAFT', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('CAIXA P/ 100 BRIGADEIROS', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('CAIXA P/ 25 BRIGADEIROS', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('CAIXA PARA 12 BRIGADEIROS- BRANCA', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('CAIXA PARA BARRA 9X16.  5X3,2', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('CAIXA PARA BARRA NATAL', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('CAIXA PARA CORAÇÃO LAPIDADO- BRANCA (3 CAVIDADES)', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('CAIXA PARA JOYSTICK- BRANCA GRANDE', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('CAIXA PARA TABLETE C / BRIGADEIROS- TIFANY', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('CAIXA PARA TORTA- GALVANOTEK G230', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('CAIXETA 4 PETÁLAS ACETATO', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('CAIXETA 4 PETALAS BRANCA/LISA', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('CAIXETA 4 PETALAS ROSAS', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('CAIXETA 4 PETALAS VINHO', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('CAIXETA MARROM FUNFESTAS', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('CAIXINHA 2 BRIGADEIROS- ORÇAMENTO', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('CAIXINHA 23X17CM', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('CAIXINHA CONE PASCOA - ORÇAMENTO', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('CALDA DE CHOCOLATE', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('CARTELA ADESIVOS - DIA DOS NAMORADOS', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('CASCA (SOMA)', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('CASQUINHA', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('CELOFANE  INCOLOR (16 X 15CM)', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('CELOFANE INCOLOR 18X20', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('CHANTILY', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('CHOCOLATE AO LEITE HERSHEYS', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('CHOCOLATE BRANCO HERSHEYS', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('CHOCOLATE EM PÓ 50% MELKEN', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('CHOCOLATE EM PÓ SICAO 50%', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('CHOCOLATE MEIO AMARGO MELKEN', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('COBERTURA AO LEITE HERSHEYS', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('COBERTURA AO LEITE MAVALÉRIO', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('COBERTURA BRANCA NORCAU PREMIUM', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('COBERTURA MEIO AMARGO HERSHEYS', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('COCO RALADO- NOSSA CRIA 500G', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('CONFEITO COLERETI', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('CONFEITO COLORETI GRANULETI', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('CONFEITO CROC. CHOCO BALL', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('CONFEITO DE AÇUCAR CORAÇÃO', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('CONFEITO DE AÇUCAR- CORAÇÕES', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('CONFEITO DE NATAL- MORELLO', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('CONFEITO MELKEN GRANULÉ AO LEITE', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('CONFEITO MELKEN VERMICELLI CHOC. AO LEITE', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('CONFETE CHOCOLATE', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('COPO BOLHA DARNEL 300 ML', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('CORANTE FAB- VERDE MENTA', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('CORANTE PARA CHOCOLATE- MIX', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('CORDÃO DE CETIM AZUL- ARTEPUNTO 50 METROS', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('CREME DE LEITE - PIRACANJUBA', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('CREME DE LEITE PIRACANJUBA', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('DISQUETE MINI', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('EMBALAGEM ARTICULADA- DUAPLAST D-305 (BROWNIE)', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('EMBALAGEM ARTICULADA QUADRADA- DUOPLAST D-405', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('EMBALAGEM ARTUCULADA QUADRADA- HIPERBRAS H-641', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('EMBALAGEM DE BOLO REDONDA G 56', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('EMBALAGEM GALVANOTEC G640 REDONDA C/ TAMPA 170 ML (TORTINHA)', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('EMBALAGEM PARA 1 BRIGADEIRO', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('EMBALAGEM PARA FATIA GALVANOTEC REF. G-630', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('EMBALAGEM PARA TORTA- G 60M', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('EMBALAGEM TRUFA', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('EMULSIFICANTE CHEF', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('EMULSIFICANTE MARVI GEL', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('ESSENCIA DE BAUNILHA', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('ESSENCIA DE BAUNILHA-ARCOLOR', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('ESSENCIA DE RUM', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('ETIQUETA "COM CARINHO"- C/100', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('ETIQUETA- FELIZ DIA DOS PAIS', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('ETIQUETA OVAL', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('ETIQUETA- PARABENS', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('ETIQUETA VAL E FABR.', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('ETIQUETA VALIDADE BRIGADEIRO', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('ETIQUETA VALIDADE CONE', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('FARINHA DE AVEIA', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('FARINHA DE AVEIA (BENGALA)', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('FARINHA DE TRIGO ROSA BRANCA', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('FECHO PRÁTICO', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('FERMENTO EM PÓ', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('FERRERO ROCHER C/ 3', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('FERRERO ROCHER C/ 8', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('FITA (SOMA DAS 9)', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('FITA CETIM- AZUL (10MX22MM)', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('FITA CETIM- AZUL FINA (10MX10MM)', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('FITA CETIM AZUL ROYAL (10MX15MM)', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('FITA CETIM- BRANCA FINA (10MX10MM)', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('FITA CETIM- BRANCA FINA (10MX7MM)', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('FITA CETIM C/ CORAÇÕES- VERMELHA (10MX22MM)', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('FITA CETIM- VERMELHA FINA (10MX10MM)', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('FITA CETIM-BRANCA (10MX15MM)', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('FITA CETIM-BRANCA (10MX22MM)', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('FITA DE CETIM- "100% ARTESANAL"- ROSA OU BRANCA  (10MX15MM)', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('FITA DE CETIM VERMELHA (10MX22MM)', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('FITA DE CETIM VINHO (10MX32MM)', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('FITA DE CETIM-PRATA (10MX22MM)', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('FITA DE CETIM-ROSA CLARO (10MX22MM)', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('FITA DE NATAL- VERMELHA/DOURADA 10MX15MM', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('FITA NATAL- VERMELHA/DESENHOS 10MX22MM', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('FITA VOAL- CREME 10MX15MM', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('FITA VOAL- VERMELHA 10MX22MM', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('FITILHO', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('FORMA BOLO CASEIRINHO M COM TAMPA', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('FORMINHA BRIGADEIRO BRANCA N05', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('FORMINHA BRIGADEIRO- MARROM Nº5 REGINA', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('FORMINHA DE BRIGADEIRO ROSA', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('FORMINHA DE BRIGADEIRO VERMELHA N4', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('FORMINHA DE BRIGADEIRO VERMELHA N4', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('FORMINHA DE PAPEL CUPCAKE', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('GANACHE', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('GELATINA S/ SABOR', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('GLICERINA BIDESTILADA', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('GOTAS FORNEÁVEIS CHOC. AO LEITE  HERSHEYS', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('GOTAS FORNEÁVEIS COBERTURA AO LEITE  HERSHEYS', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('GRANULADO CHOCOLATE DORI', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('KINDER BUENO BRANCO', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('KINDER BUENO PRETO', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('KIT CESTA', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('KIT KAT', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('LAÇO FACIL XADREZ- NATAL', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('LACRE DE SEGURANÇA', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('LEITE CONDENSADO 395G PIRACANJUBA', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('LEITE CONDENSADO ITALAC- GOURMET', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('LEITE DE COCO', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('LEITE EM PÓ NINHO INSTANTANEO', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('LIMÃO', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('MANGA DE CONFEITAR', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('MANTEIGA SEM SAL- 200GRS', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('MARACUJA FRUTA', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('MARMITA DE ALUMINIO', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('MASSA BOLO DE AVEIA', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('MASSA BOLO DE FARINHA DE TRIGO', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('MASSA CASEIRINHO CHOCOLATE', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('MINI BROWNIE (SEM EMBALAGEM)', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('MORANGO FRUTA', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('NUTELLA', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('OLEO DE GIRASSOL', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('OVOS', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('PAPEL CELOFANI POLI ESCOLAR-AZUL 90 X 100CM', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('PAPEL CHUMBO', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('PAPEL CHUMBO LISO- 8CM X 7,8CM', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('PAPEL DE SEDA NATAL- C/5 FOLHAS', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('PAPEL PRESENTE DIA DOS NAMORADOS 69X69', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('PAPEL SEDA - BEGE - 49 X 69CM', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('PAPEL SEDA - BRANCO C/ CORAÇÃO- 49 X 69CM', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('PLÁSTICO PVC', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('PÓ PARA DECORAÇÃO- BRONZE', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('PÓ PARA DECORAÇÃO MARSALA- SHINE', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('PÓ PARA DECORAÇÃO OURO ANTIGO- BRILHANTE', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('PÓ PARA DECORAÇÃO PRETO- BRILHANTE', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('PÓ PARA DECORAÇÃO ROSA- BRILHANTE', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('PÓ PARA PREPARO DE MORANGO- MAVALÉRIO', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('POTE QUADRADO C/ TAMPA 220 ML- PLASTI LÂNIA', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('POTE QUADRADO C/TAMPA- PRAFESTA (BROWNIE)', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('POTE REDONDO 250ML- PRAFESTA (BOLO DE POTE)', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('POTE REDONDO COM LACRE 250ML- PRAFESTA (BOLO DE POTE)', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('RAFAELO', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('RECHEIO BEIJINHO', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('RECHEIO CHOCOLATE AO LEITE', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('RECHEIO CHOCOLATE BRANCO', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('RECHEIO CREMOSO DE MARACUJÁ', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('RECHEIO FERRERO', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('RECHEIO NINHO', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('RECHEIO TRUFA DE MARACUJÁ', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('RECHEIOS- CÁLCULO (BEIJINHO, AO LEITE, NINHO E TRUFA)- RECEITA CHOCOLATES', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('ROSA ARTIFICIAL', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('SACO KRAFT 23,5X29,5X 12 CM', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('SACOLA KRAFT CROMUS- G 32 X 26,5 X 13CM', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('SACOLA KRAFT CROMUS- GG 39 X 32 X 16CM', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('SACOLA KRAFT CROMUS- M 26 X 19,5 X 9,5', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('SACOLA KRAFT CROMUS M- FELIZ NATAL', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('SACOLA KRAFT CROMUS- P 21,5X 15 X 8 CM', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('SAL', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('SAQUINHO 12 X 18 + ABA', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('SAQUINHO ADESIVO 10X17- CROMUS', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('SAQUINHO ADESIVO CROMUS 10X14 + ABA', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('SAQUINHO CROMUS 10 X 15CM', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('SAQUINHO CROMUS 11 X 19,5 CM', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('SAQUINHO NATAL- CROMUS 10X19,5', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('SAQUINHO TEMA PASCOA CROMUS 11X19,5', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('TAG DK ARTESANE', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('TAG KRAFT "PRODUTO ARTESANAL"', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('TRUFA CHOCOLATE', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('TRUFA DE MORANGO', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('XEREM DE AMENDOIM', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('BROWNIE RECHEADO- NINHO C/ NUTELLA (EMBALADO)', 2, 1, 1);
    insert into produto (descricao_basica, id_tipo_produto, id_unidade_medida, status) values ('BROWNIE RECHEADO- BRIGADEIRO (EMBALADO)', 2, 1, 1);
end //

-- Inserir FORMA DE VENDA
insert into forma_venda (nome) values ('IFOOD'), ('WHATSAPP'), ('INSTAGRAM');

