name: Build Docker Image

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Seleciona JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: maven

    - name: Instalando dependencias e construindo projeto
      run: mvn clean install -DskipTests
    
    - name: Registrando horario de geracao da imagem
      run: echo "CURRENT_DATETIME=$(date +%Y%m%d-%H:%M)" >> $GITHUB_ENV
    - name: Constroindo imagem Docker
      run: docker build -t liberato/lazuli-web:$CURRENT_DATETIME .
      
    - name: Publicando imagem Docker
      run: docker push ghcr.io/liberatov13/liberato/lazuli-web:$CURRENT_DATETIME
