name: Dev

on:
  workflow_dispatch:

jobs:
  build-project:
    runs-on: ubuntu-latest

    steps:
    - name: "Clonando projeto"
      uses: actions/checkout@v3

    - name: "Selecionando JDK 8"
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: maven

    - name: "Instalando dependencias e construindo projeto"
      run: mvn clean install -DskipTests
    
    - name: "Salvando executavel"
      uses: actions/upload-artifact@v3
      with:
        name: lazuli.jar
        path: target/

  build-docker-image:
    needs: build-project
    runs-on: ubuntu-latest

    steps:

    - name: "Obtendo executavel"
      uses: actions/download-artifact@v3
      with:
        name: lazuli.jar
    
    - name: "Construindo Docker image de dev"
      run: docker build -t ghcr.io/liberatov13/lazuli:dev .

    - name: "Fazendo login no GitHub Container Registry"
      uses: azure/docker-login@v1

      with:
        login-server: ghcr.io
        username: liberatov13
        password: ${{ secrets.GH_LAZULI_WEB_TOKEN }}

    - name: "Publicando Docker Image de dev"
      run: docker push ghcr.io/liberatov13/lazuli:dev
