name: Main

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build-project:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: "Selecionando JDK 8"
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: maven

    - name: "Instalando dependencias e construindo projeto"
      run: mvn clean install -DskipTests

  build-docker-image:
    needs: build-project
    runs-on: ubuntu-latest

    steps:
    - name: "Construindo Docker image da master"
      if: ${{ github.ref_name }} == master
      run: docker build -t ghcr.io/liberatov13/lazuli .

    - name: "Construindo Docker image de dev"
      if: ${{ github.ref_name }} != master
      run: docker build -t ghcr.io/liberatov13/lazuli:dev .

    - name: "Fazendo login no GitHub Container Registry"
      uses: azure/docker-login@v1

      with:
        login-server: ghcr.io
        username: liberatov13
        password: ${{ secrets.GH_LAZULI_WEB_TOKEN }}

    - name: "Publicando Docker Image"
      run: docker push ghcr.io/liberatov13/lazuli
