name: master

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: "[01] Clonando projeto"
      uses: actions/checkout@v3

    - name: "[02] Selecionando JDK 8"
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: maven

    - name: "[03] Instalando dependencias e construindo projeto"
      run: mvn clean install -DskipTests

    - name: "[04] Construindo Docker image da master"
      run: docker build -t ghcr.io/liberatov13/lazuli .

    - name: "[05] Fazendo login no GitHub Container Registry"
      uses: azure/docker-login@v1
      with:
        login-server: ghcr.io
        username: liberatov13
        password: ${{ secrets.GH_LAZULI_WEB_TOKEN }}

    - name: "[06] Publicando Docker Image da master"
      run: docker push ghcr.io/liberatov13/lazuli
